version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Your_strong_Password123'
    ports:
      - '1433:1433'
    volumes:
      - mssql_data:/var/opt/mssql

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env.example
    depends_on:
      - mssql
    ports:
      - '8000:8000'

volumes:
  mssql_data:
